version: '3'

services:
  greenlight:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - log:/usr/src/app/log
    links:
      - db
  db:
    image: postgres:9.5
    restart: unless-stopped
    ports:
      - 5432
    volumes: 
      - 'dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=greenlight_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes: 
  dbdata:
  log: