default: &default
  pool: 5
  timeout: 5000
  adapter: <%= ENV['DB_ADAPTER'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>


development:
  <<: *default


test:
  <<: *default

production:
  <<: *default

