default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: db/development.postgresql

test:
  <<: *default
  adapter: postgresql
  database: db/test.postgresql

# Use sqlite in production by default. Greenlight supports
production:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
